"""rename_merchant_to_paid_to_add_tax_id_drop_title

Revision ID: 296f93eb1da7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 08:52:09.189187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '296f93eb1da7'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('paid_to', sa.String(length=255), nullable=True))
    op.add_column('expenses', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.alter_column('expenses', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_column('expenses', 'merchant_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('merchant_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.alter_column('expenses', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('expenses', 'tax_id')
    op.drop_column('expenses', 'paid_to')
    # ### end Alembic commands ###
