"""create_initial_database_schema

Revision ID: cbb57baabb25
Revises: 
Create Date: 2026-06-13 17:03:25.646811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbb57baabb25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_th', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_categories_name_en'), 'categories', ['name_en'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('expenses',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('receipt_time', sa.Time(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('input_method', sa.String(length=50), nullable=False),
    sa.Column('language_detected', sa.String(length=20), nullable=True),
    sa.Column('ai_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('ai_status', sa.String(length=30), nullable=False),
    sa.Column('ai_raw_response', sa.JSON(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_user_receipt_date', 'expenses', ['user_id', 'receipt_date'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_deleted_at'), 'expenses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expenses_receipt_date'), 'expenses', ['receipt_date'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('expense_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('expense_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_th', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_items_category_id'), 'expense_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_expense_items_deleted_at'), 'expense_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expense_items_expense_id'), 'expense_items', ['expense_id'], unique=False)
    op.create_table('receipt_files',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('expense_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('upload_status', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_files_deleted_at'), 'receipt_files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_receipt_files_expense_id'), 'receipt_files', ['expense_id'], unique=False)
    op.create_index(op.f('ix_receipt_files_file_hash'), 'receipt_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_receipt_files_stored_filename'), 'receipt_files', ['stored_filename'], unique=True)
    op.create_index(op.f('ix_receipt_files_user_id'), 'receipt_files', ['user_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('expense_item_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=20), nullable=False),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('translation_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_item_id'], ['expense_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_translations_source_target_lang', 'translations', ['source_language', 'target_language'], unique=False)
    op.create_index(op.f('ix_translations_deleted_at'), 'translations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_translations_expense_item_id'), 'translations', ['expense_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_expense_item_id'), table_name='translations')
    op.drop_index(op.f('ix_translations_deleted_at'), table_name='translations')
    op.drop_index('idx_translations_source_target_lang', table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_receipt_files_user_id'), table_name='receipt_files')
    op.drop_index(op.f('ix_receipt_files_stored_filename'), table_name='receipt_files')
    op.drop_index(op.f('ix_receipt_files_file_hash'), table_name='receipt_files')
    op.drop_index(op.f('ix_receipt_files_expense_id'), table_name='receipt_files')
    op.drop_index(op.f('ix_receipt_files_deleted_at'), table_name='receipt_files')
    op.drop_table('receipt_files')
    op.drop_index(op.f('ix_expense_items_expense_id'), table_name='expense_items')
    op.drop_index(op.f('ix_expense_items_deleted_at'), table_name='expense_items')
    op.drop_index(op.f('ix_expense_items_category_id'), table_name='expense_items')
    op.drop_table('expense_items')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_receipt_date'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_deleted_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index('idx_expenses_user_receipt_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name_en'), table_name='categories')
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
